'use strict';
const $=id=>document.getElementById(id), controls=[...document.querySelectorAll('textarea,input:not([type=file])')], key='exs290-search-review-revise-v1';
let images={};
function status(t){$('status').textContent=t}
function snapshot(){return {version:1,fields:Object.fromEntries(controls.map(e=>[e.id,e.value])),images}}
function save(){try{localStorage.setItem(key,JSON.stringify(snapshot()));status('Saved in this browser. Save a backup to keep a portable copy.')}catch{status('Browser storage is unavailable or full. Save a project backup now to preserve your work.')}}
function apply(data){if(data.version!==1||!data.fields||typeof data.fields!=='object')throw Error('Unsupported backup');for(const e of controls)e.value=typeof data.fields[e.id]==='string'?data.fields[e.id]:'';images={};for(const prefix of ['first','revised']){let v=data.images?.[prefix];if(typeof v==='string'&&/^data:image\/(png|jpeg);base64,/.test(v)&&v.length<12000000)images[prefix]=v;preview(prefix)}}
function preview(prefix){let e=$(prefix+'preview');e.hidden=!images[prefix];if(images[prefix])e.src=images[prefix];else e.removeAttribute('src')}
try{const old=localStorage.getItem(key);if(old){apply(JSON.parse(old));status('Restored your saved browser workspace.')}}catch{status('No saved workspace could be restored. You can load a project backup.')}
for(const e of controls){if($(e.id+'-help'))e.setAttribute('aria-describedby',e.id+'-help');e.addEventListener('input',save)}
for(const prefix of ['first','revised'])$(prefix+'image').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg'].includes(f.type)||f.size>8*1024*1024){status('Choose a PNG or JPEG no larger than 8 MB.');e.target.value='';return}try{const data=await new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});images[prefix]=data;preview(prefix);save()}catch{status('The image could not be loaded. Try another file or use typed evidence.')}});
for(const b of document.querySelectorAll('[data-remove]'))b.onclick=()=>{const p=b.dataset.remove;delete images[p];$(p+'image').value='';preview(p);save()};
$('feedbackButton').onclick=()=>{let prompts=[];let q=$('firstquery').value; if(!q.trim())prompts.push('Record the exact executed search before evaluating its structure.');if(!/\bOR\b/.test(q))prompts.push('If the database supports Boolean searching, consider whether OR could combine useful synonyms for the same concept. Check its search guidance.');if(/\bAND\b/.test(q)&&/\bOR\b/.test(q)&&!q.includes('('))prompts.push('Check whether parentheses would clarify synonym groups in this database. Syntax differs across databases.');if($('concept3').value.trim())prompts.push('Consider whether the third concept excludes relevant studies. Test removing it only if your results give you a reason.');if($('firstfilters').value.trim()&&!/^none\.?$/i.test($('firstfilters').value.trim()))prompts.push('Consider what your filters exclude. Are those exclusions justified by your question?');prompts.push('Inspect the actual results: which titles or abstracts show a mismatch, and which show a useful match? Name specific evidence.','If results are too broad, test one justified concept or field restriction. If too narrow, test one synonym, concept removal, or filter change.','Change one meaningful feature when feasible so you can interpret its effect. More or fewer results alone does not mean a better search.');$('feedbackOutput').replaceChildren();const ul=document.createElement('ul');for(const t of prompts){let li=document.createElement('li');li.textContent=t;ul.append(li)}$('feedbackOutput').append(ul);$('feedbackRecord').value=prompts.join('\n\n');save()};
function issues(){let a=[];for(const e of controls){if(['concept3','difficulty','firsttyped','revisedtyped','firstcaption','revisedcaption'].includes(e.id))continue;if(!e.value.trim())a.push(document.querySelector(`label[for="${e.id}"]`).textContent+' is blank.')}for(const p of ['first','revised']){if(!images[p]&&!$(p+'typed').value.trim())a.push(p+' search needs an image or typed evidence.');if(images[p]&&!$(p+'caption').value.trim())a.push(p+' image needs a typed description.')}for(const p of ['primary','review','rejected'])if($(p+'url').value&&!/^https?:\/\//i.test($(p+'url').value))a.push(p+' full-text link needs http:// or https://.');return a}
$('check').onclick=()=>{let a=issues();$('checks').replaceChildren();let p=document.createElement('p');p.textContent=a.length?'Records to review (this checks completeness, not accuracy):':'All expected records are present. Personally verify accuracy, sources, and PDF readability.';$('checks').append(p);if(a.length){let ul=document.createElement('ul');for(const t of a){let li=document.createElement('li');li.textContent=t;ul.append(li)}$('checks').append(ul)}};
$('backup').onclick=()=>{let blob=new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='research-search-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Project backup downloaded. Keep it somewhere you can find again.')};
$('restore').onchange=async e=>{let f=e.target.files[0];if(!f)return;if(f.size>25000000){status('Backup is too large.');return}try{let d=JSON.parse(await f.text());if(d.version!==1||!d.fields)throw Error();if(!confirm('Replace the current workspace with this backup? Save your current backup first if needed.'))return;apply(d);save()}catch{status('This file is not a supported research project backup.')}e.target.value=''};
function report(){const r=$('report');r.replaceChildren();let actions=document.createElement('div');actions.className='actions no-print';for(const [text,fn] of [['Back to workspace',()=>{$('report').hidden=true;$('workspace').hidden=false;$('export').focus()}],['Print / Save PDF',()=>window.print()]]){let b=document.createElement('button');b.textContent=text;b.onclick=fn;actions.append(b)}r.append(actions);let h=document.createElement('h1');h.textContent='Research Search Process';r.append(h);let sub=document.createElement('p');sub.textContent='Search → Review → Revise | EXS290';r.append(sub);for(const section of document.querySelectorAll('#workspace section')){let s=document.createElement('div');s.className='report-section';let h=document.createElement('h2');h.textContent=section.dataset.title;s.append(h);for(const item of section.querySelectorAll('h3,textarea,input:not([type=file])')){if(item.tagName==='H3'){let h=document.createElement('h3');h.textContent=item.textContent;s.append(h);continue}let row=document.createElement('div');row.className='record';let b=document.createElement('b');b.textContent=document.querySelector(`label[for="${item.id}"]`).textContent;let p=document.createElement('p');if(item.type==='url'&&/^https?:\/\//i.test(item.value)){let a=document.createElement('a');a.href=item.value;a.textContent=item.value;p.append(a)}else p.textContent=item.value||'[Not recorded]';row.append(b,p);s.append(row)}let prefix=section.id==='first'?'first':section.id==='revised'?'revised':null;if(prefix&&images[prefix]){let img=document.createElement('img');img.className='report-image';img.src=images[prefix];img.alt=$(prefix+'caption').value||'Search evidence';s.append(img)}r.append(s)}$('workspace').hidden=true;r.hidden=false;window.scrollTo(0,0);r.querySelector('button').focus()}
$('export').onclick=()=>{save();report()};
