'use strict';
const $=id=>document.getElementById(id), controls=[...document.querySelectorAll('textarea,input:not([type=file])')], key='exs290-search-review-revise-v1';
let images={}, firstAttempt=null;
function status(t){$('status').textContent=t}
function snapshot(){return {version:1,fields:Object.fromEntries(controls.map(e=>[e.id,e.value])),images,firstAttempt}}
function save(){try{localStorage.setItem(key,JSON.stringify(snapshot()));status('Saved in this browser. Save a backup to keep a portable copy.')}catch{status('Browser storage is unavailable or full. Save a project backup now to preserve your work.')}}
function validImage(v){return typeof v==='string'&&/^data:image\/(png|jpeg);base64,/.test(v)&&v.length<12000000}
function imageList(v){return (Array.isArray(v)?v:typeof v==='string'?[v]:[]).filter(validImage).slice(0,4)}
function lockFirst(){if(!firstAttempt)return;for(const e of controls)if(e.id!=='correction'&&(e.closest('#plan')||e.closest('#first')))e.readOnly=true;$('firstimage').disabled=true;document.querySelector('[data-remove="first"]').disabled=true;$('feedbackButton').disabled=true;$('firstSaved').textContent='First attempt saved. These entries are preserved in your report. Use the optional corrections box for later corrections and Step 4 for your revised search.';}
function apply(data){if(data.version!==1||!data.fields||typeof data.fields!=='object')throw Error('Unsupported backup');for(const e of controls)e.value=typeof data.fields[e.id]==='string'?data.fields[e.id]:'';images={};for(const prefix of ['first','revised']){images[prefix]=imageList(data.images?.[prefix]);preview(prefix)}firstAttempt=null;for(const e of controls)e.readOnly=false;$('firstimage').disabled=false;document.querySelector('[data-remove="first"]').disabled=false;$('feedbackButton').disabled=false;$('firstSaved').textContent='';if(data.firstAttempt&&typeof data.firstAttempt.fields==='object'){firstAttempt={fields:{},images:imageList(data.firstAttempt.images)};for(const e of controls)if(e.closest('#plan')||e.closest('#first')){firstAttempt.fields[e.id]=typeof data.firstAttempt.fields[e.id]==='string'?data.firstAttempt.fields[e.id]:'';e.value=firstAttempt.fields[e.id]}images.first=firstAttempt.images;preview('first');lockFirst()}}
function preview(prefix){let e=$(prefix+'preview');e.replaceChildren();e.hidden=!images[prefix]?.length;for(const [i,v] of (images[prefix]||[]).entries()){let img=document.createElement('img');img.src=v;img.alt='Search screenshot '+(i+1)+'. See the typed screenshot description below.';e.append(img)}}
try{const old=localStorage.getItem(key);if(old){apply(JSON.parse(old));status('Restored your saved browser workspace.')}}catch{status('No saved workspace could be restored. You can load a project backup.')}
for(const e of controls){if($(e.id+'-help'))e.setAttribute('aria-describedby',e.id+'-help');e.addEventListener('input',save)}
for(const prefix of ['first','revised'])$(prefix+'image').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;if(files.length>4||files.some(f=>!['image/png','image/jpeg'].includes(f.type)||f.size>8*1024*1024)){status('Choose up to four PNG or JPEG screenshots, each no larger than 8 MB.');e.target.value='';return}try{const data=await Promise.all(files.map(f=>new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})));images[prefix]=data;preview(prefix);save()}catch{status('Screenshots could not be loaded. Try another file or use typed evidence.')}});
for(const b of document.querySelectorAll('[data-remove]'))b.onclick=()=>{const p=b.dataset.remove;images[p]=[];$(p+'image').value='';preview(p);save()};
function firstIssues(){let missing=[];for(const id of ['name','question','components','concept1','concept2','fit','prediction','firstdatabase','firstdate','firstquery','firstfilters','observations'])if(!$(id).value.trim())missing.push(document.querySelector(`label[for="${id}"]`).textContent);if(!images.first?.length&&!$('firsttyped').value.trim())missing.push('First-search screenshots or typed evidence');if(images.first?.length&&!$('firstcaption').value.trim())missing.push('Description of your first-search screenshots');return missing}
$('feedbackButton').onclick=()=>{if(firstAttempt)return;const missing=firstIssues();if(missing.length){$('feedbackOutput').textContent='Before feedback, complete: '+missing.join('; ')+'.';return}firstAttempt={fields:Object.fromEntries(controls.filter(e=>e.closest('#plan')||e.closest('#first')).map(e=>[e.id,e.value])),images:[...(images.first||[])]};lockFirst();let prompts=[];let q=$('firstquery').value; if(!q.trim())prompts.push('Record the exact executed search before evaluating its structure.');if(!/\bOR\b/.test(q))prompts.push('If the database supports Boolean searching, consider whether OR could combine useful synonyms for the same concept. Check its search guidance.');if(/\bAND\b/.test(q)&&/\bOR\b/.test(q)&&!q.includes('('))prompts.push('Check whether parentheses would clarify synonym groups in this database. Syntax differs across databases.');if($('concept3').value.trim())prompts.push('Consider whether the third concept excludes relevant studies. Test removing it only if your results give you a reason.');if($('firstfilters').value.trim()&&!/^none\.?$/i.test($('firstfilters').value.trim()))prompts.push('Consider what your filters exclude. Are those exclusions justified by your question?');prompts.push('Inspect the actual results: which titles or abstracts show a mismatch, and which show a useful match? Name specific evidence.','If results are too broad, test one justified concept or field restriction. If too narrow, test one synonym, concept removal, or filter change.','Change one meaningful feature when feasible so you can interpret its effect. More or fewer results alone does not mean a better search.');$('feedbackOutput').replaceChildren();const ul=document.createElement('ul');for(const t of prompts){let li=document.createElement('li');li.textContent=t;ul.append(li)}$('feedbackOutput').append(ul);$('feedbackRecord').value=prompts.join('\n\n');save()};
function issues(){let a=[];for(const e of controls){if(['concept3','difficulty','firsttyped','revisedtyped','firstcaption','revisedcaption','correction'].includes(e.id))continue;if(!e.value.trim())a.push(document.querySelector(`label[for="${e.id}"]`).textContent+' is blank.')}for(const p of ['first','revised']){if(!images[p]?.length&&!$(p+'typed').value.trim())a.push(p+' search needs an image or typed evidence.');if(images[p]?.length&&!$(p+'caption').value.trim())a.push(p+' image needs a typed description.')}for(const p of ['primary','review','rejected'])if($(p+'url').value&&!/^https?:\/\//i.test($(p+'url').value))a.push(p+' full-text link needs http:// or https://.');return a}
function openField(id){const field=$(id);if(!field)return;showPanel(field.closest('section').id,true);const candidate=field.closest('[id^="candidate-"]');if(candidate)showCandidate(candidate.id.replace('candidate-',''));for(let p=field.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;field.focus();field.scrollIntoView({block:'center'});}
$('check').onclick=()=>{const items=[];for(const e of controls){if(['concept3','difficulty','firsttyped','revisedtyped','firstcaption','revisedcaption','correction'].includes(e.id))continue;if(!e.value.trim())items.push({id:e.id,text:document.querySelector('label[for="'+e.id+'"]').textContent+' is blank.'});}for(const p of ['first','revised']){if(!images[p]?.length&&!$(p+'typed').value.trim())items.push({id:p+'typed',text:p+' search needs screenshots or typed evidence.'});if(images[p]?.length&&!$(p+'caption').value.trim())items.push({id:p+'caption',text:p+' screenshots need a typed description.'});}for(const p of ['primary','review','rejected'])if($(p+'url').value&&!/^https?:\\/\\//i.test($(p+'url').value))items.push({id:p+'url',text:p+' link needs http:// or https://.'});const host=$('checks');host.replaceChildren();const intro=document.createElement('p');intro.textContent=items.length?'Select an item to open its section and field. These checks measure completeness, not accuracy.':'No blank required records found. Verify accuracy, evidence, sources, and PDF readability yourself.';host.append(intro);const ul=document.createElement('ul');for(const item of items){const li=document.createElement('li'),b=document.createElement('button');b.type='button';b.className='field-link';b.textContent=item.text;b.onclick=()=>openField(item.id);li.append(b);ul.append(li);}host.append(ul);};
$('backup').onclick=()=>{let blob=new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='research-search-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Project backup downloaded. Keep it somewhere you can find again.')};
$('restore').onchange=async e=>{let f=e.target.files[0];if(!f)return;if(f.size>110000000){status('Backup is too large.');return}try{let d=JSON.parse(await f.text());if(d.version!==1||!d.fields)throw Error();if(!confirm('Replace the current workspace with this backup? Save your current backup first if needed.'))return;apply(d);save()}catch{status('This file is not a supported research project backup.')}e.target.value=''};
function report(){const r=$('report');r.replaceChildren();let actions=document.createElement('div');actions.className='actions no-print';for(const [text,fn] of [['Back to workspace',()=>{$('report').hidden=true;$('workspace').hidden=false;$('export').focus()}],['Print / Save PDF',()=>window.print()]]){let b=document.createElement('button');b.textContent=text;b.onclick=fn;actions.append(b)}r.append(actions);let h=document.createElement('h1');h.textContent='Research Search Process';r.append(h);let sub=document.createElement('p');sub.textContent='Search → Review → Revise | EXS290';r.append(sub);for(const section of document.querySelectorAll('#workspace section')){let s=document.createElement('div');s.className='report-section';let h=document.createElement('h2');h.textContent=section.dataset.title;s.append(h);for(const item of section.querySelectorAll('h3,textarea:not(#correction),input:not([type=file])')){if(item.tagName==='H3'){let h=document.createElement('h3');h.textContent=item.textContent;s.append(h);continue}let row=document.createElement('div');row.className='record';let b=document.createElement('b');b.textContent=document.querySelector(`label[for="${item.id}"]`).textContent;let p=document.createElement('p');if(item.type==='url'&&/^https?:\/\//i.test(item.value)){let a=document.createElement('a');a.href=item.value;a.textContent=item.value;p.append(a)}else p.textContent=item.value||'[Not recorded]';row.append(b,p);s.append(row)}let prefix=section.id==='first'?'first':section.id==='revised'?'revised':null;if(prefix&&images[prefix]?.length){for(const [i,v] of images[prefix].entries()){let figure=document.createElement('figure');figure.style.margin='12px 0';let img=document.createElement('img');img.className='report-image';img.src=v;img.alt=$(prefix+'caption').value||'Search evidence';let caption=document.createElement('figcaption');caption.textContent='Search screenshot '+(i+1);figure.append(img,caption);s.append(figure)}}if(section.id==='first'&&firstAttempt){let note=document.createElement('p');note.textContent='Original first attempt preserved when feedback was requested.';s.append(note);if($('correction').value.trim()){let row=document.createElement('div');row.className='record';let b=document.createElement('b');b.textContent='Later correction to the original attempt';let p=document.createElement('p');p.textContent=$('correction').value;row.append(b,p);s.append(row)}}r.append(s)}$('workspace').hidden=true;r.hidden=false;window.scrollTo(0,0);r.querySelector('button').focus()}
$('export').onclick=()=>{save();report()};

// Section navigation is independent of completeness and feedback checks.
const tabs=[...document.querySelectorAll('.workspace-tabs [role="tab"]')];
function showPanel(id,focusTab=false){const chosen=tabs.find(t=>t.dataset.panel===id)||tabs[0];for(const t of tabs){const selected=t===chosen;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;$(t.dataset.panel).hidden=!selected;}if(focusTab)chosen.focus();}
for(const [i,t] of tabs.entries()){t.addEventListener('click',()=>showPanel(t.dataset.panel));t.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();showPanel(tabs[next].dataset.panel,true);});const bar=document.createElement('div');bar.className='panel-navigation';for(const [index,label] of [[i-1,'Previous section'],[i+1,'Next section']])if(tabs[index]){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=label;b.onclick=()=>{showPanel(tabs[index].dataset.panel,true);document.querySelector('.workspace-tabs').scrollIntoView({block:'start'});};bar.append(b);}$(t.dataset.panel).append(bar);}
showPanel(location.hash.slice(1));
window.addEventListener('hashchange',()=>showPanel(location.hash.slice(1)));

const candidateTabs=[...document.querySelectorAll('.candidate-tabs [role=tab]')];
function showCandidate(id,focus=false){const chosen=candidateTabs.find(t=>t.dataset.candidate===id)||candidateTabs[0];for(const t of candidateTabs){const selected=t===chosen;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;$('candidate-'+t.dataset.candidate).hidden=!selected;}$('candidate-position').textContent='Candidate '+(candidateTabs.indexOf(chosen)+1)+' of 3: '+chosen.textContent;if(focus)chosen.focus();}
for(const [i,t]of candidateTabs.entries()){t.onclick=()=>showCandidate(t.dataset.candidate);t.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%3;else if(e.key==='ArrowLeft')n=(i+2)%3;else if(e.key==='Home')n=0;else if(e.key==='End')n=2;else return;e.preventDefault();showCandidate(candidateTabs[n].dataset.candidate,true);});}
$('quickBackup').onclick=()=>$('backup').click();
showCandidate('primary');
