'use strict';
const $=id=>document.getElementById(id), KEY='exs290-evidence-appraisal-v1';
const common=[['citation','Imported candidate citation (verify and separate details below)'],['title','Article title'],['authors','Authors'],['year','Publication year'],['journal','Journal / publisher'],['doi','DOI, if available'],['link','Full-text link'],['access','Full-text access check and date'],['design','Specific study design or source type, and evidence supporting it'],['population','Earlier combined PICO notes (optional; separate the components below)'],['methods','Exact short methods excerpt and precise locator'],['methodMeaning','What do those methods tell you about how this evidence was produced?'],['result','Exact relevant result excerpt, including statistical support where applicable, and precise locator'],['interpretation','What does this finding mean? Explain in your own words.'],['strengthEvidence','One specific methodological strength: source evidence and locator'],['strengthMeaning','How does that strength affect confidence in this finding?'],['concernEvidence','One specific concern or limitation: source evidence and locator'],['consequence','What does that concern change about interpretation or use of this finding?'],['relevance','How does this source fit your question? Identify important mismatches.']];
const deepFields=[['deepEvidence','Evidence and locator for a consequential methodological issue'],['deepOrigin','What do the authors acknowledge, and what do you independently notice?'],['deepMeaning','How does this affect credibility, precision, applicability, or more than one? Explain.'],['weight','How does this change the weight you would give this source?']];
const matrixFields=[['picoP','Population actually studied (P)'],['picoI','Intervention or exposure examined (I)'],['picoC','Comparison actually used (C)'],['picoO','Outcome concept examined (O)'],['measure','Exact outcome measure, units, and time frame'],['finding','Relevant finding: concise summary and reported values'],['stats','Statistical support: p-value, confidence interval, effect size, or other information reported'],['analysis','Statistical analysis used for this finding, if reported']];
const matrixColumns=[['title','Article title'],['authors','Authors'],['year','Year'],['link','Full-text link'],['type','Source family'],['design','Design'],['database','Database / discovery route'],['keywords','Search terms'],...matrixFields.slice(0,5),...matrixFields.slice(5),['concernEvidence','Concern / limitation and locator'],['consequence','Effect on interpretation'],['relevance','Question fit'],['decision','Selection decision']];
let state={kind:'exs290-appraisal',version:1,fields:{},sources:[]};
function status(t){$('status').textContent=t;}
function save(){for(const k of ['name','question','changes','overlap','selection','ai'])state.fields[k]=$(k).value;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{status('Browser storage is unavailable or full. Save a work backup to preserve your entries.');}}
function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
function input(parent,s,key,label,selectOptions){const id='s'+s.id+'-'+key,l=el('label',label);l.htmlFor=id;parent.append(l);const n=el(selectOptions?'select':(['title','authors','year','journal','doi','link','access'].includes(key)?'input':'textarea'));n.id=id;if(selectOptions)for(const [v,t]of selectOptions){const o=el('option',t);o.value=v;n.append(o);}n.value=s.fields[key]||'';n.addEventListener('input',()=>{s.fields[key]=n.value;save();renderMatrix();});parent.append(n);return n;}
function prompts(s){const f=s.fields,p=[];if(f.type==='primary'){p.push(f.assignment==='assigned'?'Check how assignment, the comparison condition, missing data, and measurement could affect the finding. Assignment alone does not establish that bias was prevented.':'Check whether your wording implies causation. What features of the actual design support or limit that interpretation?');}else if(f.type==='review')p.push('Check databases and search dates, eligibility rules, appraisal of included studies, and how findings were combined. Do differences among included studies affect the synthesis?');else p.push('Check how evidence was selected and how recommendations were developed. Distinguish supporting research from expert judgment and disclose conflicts or missing process information.');
const concerns={sample:'Is the sample concern about precision, representation, or both? Locate the specific evidence and explain the consequence.',measurement:'Check what the measure captures, how consistently it was collected, and whether it matches your intended outcome.',bias:'Identify the specific pathway through which selection, confounding, blinding, missing data, or reporting could influence the result.',applicability:'Which population, setting, dose, outcome, or time frame differs from your question? Explain how that limits use.',reporting:'Separate information not reported from evidence that a method was not used. What remains uncertain?',other:'Explain how the concern could influence this specific result or its use. Avoid a generic limitation list.'};p.push(concerns[f.concern]||concerns.other);p.push('Recheck the exact comparison, units, time point, and statistical information. A significant result is not automatically practically important; a nonsignificant result does not establish equivalence.');return p;}
function render(){const host=$('sources');host.replaceChildren();state.sources.forEach((s,index)=>{const box=el('fieldset'),legend=el('legend','Article '+(index+1)+(s.fields.title?' — '+s.fields.title:''));box.append(legend);input(box,s,'type','Source family',[['','Choose a source family'],['primary','Primary study'],['review','Systematic review / meta-analysis'],['position','Position stand (when allowed)']]);
const guide=el('p',s.fields.type==='review'?'Review methods: examine searching, eligibility, study appraisal, and synthesis.':s.fields.type==='position'?'Position stand: examine evidence selection, recommendation development, and conflicts of interest.':'Primary methods: examine recruitment, assignment or observation, comparison, measurement, and analysis.');guide.className='hint';box.append(guide);const groups=[['1. Identify and verify the source',common.slice(0,9)],['2. Examine the methods',common.slice(9,12)],['3. Interpret a relevant finding',common.slice(12,14)],['4. Judge strengths, concerns, and fit',common.slice(14)]];for(const [heading,fields]of groups){const panel=el('details');panel.open=index===0&&heading.startsWith('1.');panel.append(el('summary',heading));for(const [k,l]of fields)input(panel,s,k,l);if(heading.startsWith('2.')){const hint=el('p','Record what this source actually studied, not your intended PICO. For a review, describe included-study scope and variation. For a position stand, describe its recommendation scope. Use Not applicable or Not reported with an explanation when needed.');hint.className='hint';panel.append(hint);for(const [k,l]of matrixFields.slice(0,5))input(panel,s,k,l);}if(heading.startsWith('3.')){panel.append(el('p','Keep the measured outcome separate from the finding. Report relevant values, units, time frame, and uncertainty; do not invent a p-value when none is reported.'));for(const [k,l]of matrixFields.slice(5,8))input(panel,s,k,l);}box.append(panel);}
input(box,s,'decision','Current selection decision',[['','Not yet decided'],['keep','Keep'],['limited','Keep with limitations'],['replace','Replace / exclude']]);input(box,s,'database','Where did you find this source? Database or other route');input(box,s,'keywords','Search terms used to find this source (if known)');input(box,s,'assignment','For a primary study, were conditions assigned or observed?',[['','Choose / not applicable'],['assigned','Assigned by researchers'],['observed','Observed / not assigned'],['na','Not applicable to this source']]);input(box,s,'concern','What is your main concern?',[['','Choose a concern'],['sample','Sample size or representation'],['measurement','Measurement'],['bias','Bias or confounding'],['applicability','Applicability'],['reporting','Incomplete reporting'],['other','Other / uncertainty']]);
const deep=el('details');deep.append(el('summary','Deeper appraisal (complete for two influential sources)'));for(const [k,l]of deepFields)input(deep,s,k,l);box.append(deep);
const feedback=el('div');feedback.className='feedback';feedback.append(el('h3','Guided feedback and revision'));feedback.append(el('p','These prompts are selected from your structured choices. They do not evaluate your article, verify your interpretation, or generate an answer.'));
{const b=el('button',s.original?'Save another checkpoint and refresh self-check prompts':'Save a checkpoint and show self-check prompts');b.addEventListener('click',()=>{save();const missing=['title','authors','year','journal','link','access','design','type','methods','methodMeaning','result','interpretation','strengthEvidence','strengthMeaning','concernEvidence','consequence','relevance','concern'].filter(k=>!s.fields[k]?.trim());if(missing.length){status('Complete source '+(index+1)+' evidence, interpretation, strength, concern, relevance, and choices before requesting prompts.');return;}if(!s.original)s.original=JSON.parse(JSON.stringify(s.fields));s.checkpoints=s.checkpoints||[];s.checkpoints.push({savedAt:new Date().toISOString(),fields:JSON.parse(JSON.stringify(s.fields)),feedback:prompts(s)});s.feedback=prompts(s);save();render();status('Checkpoint saved. Your article record remains editable. Explain important changes below; you do not need to wait for instructor feedback.');});feedback.append(b);}if(s.original){feedback.append(el('p','Earlier appraisal preserved. Edit your current record above and explain meaningful changes below. Peer and instructor feedback can be added later; it is not required to continue.'));const ul=el('ul');for(const p of s.feedback)ul.append(el('li',p));feedback.append(ul);for(const [k,l]of [['response','Which prompts will you adopt, adapt, or decline, and why?'],['external','Peer / instructor feedback (optional): who provided it and what was suggested?'],['revision','Your revised interpretation or appraisal: identify what changed and why'],['next','What remains uncertain, and what will you check next?']]){const id='s'+s.id+'-'+k,lbl=el('label',l);lbl.htmlFor=id;const n=el('textarea');n.id=id;n.value=s[k]||'';n.addEventListener('input',()=>{s[k]=n.value;save();});feedback.append(lbl,n);}}
box.append(feedback);host.append(box);const type=$('s'+s.id+'-type');type.addEventListener('change',render);});renderMatrix();}

function matrixRows(){return state.sources.map(s=>matrixColumns.map(([k])=>s.fields[k]||''));}
function renderMatrix(){const host=$('matrix');if(!host)return;host.replaceChildren();$('sourceCount').textContent=state.sources.length+' article record'+(state.sources.length===1?'':'s')+' in this workspace.';if(!state.sources.length){host.append(el('p','No article records yet. Add your first article below.'));return;}const table=el('table');table.append(el('caption','Running evidence table: generated from your current article records'));const head=el('thead'),hr=el('tr');for(const [,label]of matrixColumns){const th=el('th',label);th.scope='col';hr.append(th);}head.append(hr);table.append(head);const body=el('tbody');state.sources.forEach((s,i)=>{const tr=el('tr');matrixColumns.forEach(([k],j)=>{const td=el(j===0?'th':'td');if(j===0)td.scope='row';const v=s.fields[k]||'';if(k==='link'&&/^https?:\/\/\S+$/.test(v)){const a=el('a','Open full text');a.href=v;a.target='_blank';a.rel='noopener';td.append(a);}else td.textContent=v||(j===0?'Article '+(i+1):'Not recorded');tr.append(td);});body.append(tr);});table.append(body);host.append(table);}
function csvCell(value){let v=String(value);if(/^[\s]*[=+@-]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"';}
function downloadCsv(){save();const rows=[['Current question',state.fields.question||''],[],matrixColumns.map(([,l])=>l),...matrixRows()];const csv='\ufeff'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=el('a');a.href=url;a.download='research-evidence-table.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Evidence table downloaded. Open the CSV in Excel or import it into Google Sheets. Spreadsheet edits do not sync back to this workspace.');}
$('csv').onclick=downloadCsv;

function add(fields={}){state.sources.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),fields});save();render();}
function apply(data){state=data;for(const k of ['name','question','changes','overlap','selection','ai'])$(k).value=state.fields[k]||'';render();}
function valid(d){return d?.kind==='exs290-appraisal'&&d.version===1&&d.fields&&Array.isArray(d.sources)&&d.sources.length<=30&&d.sources.every(s=>typeof s.id==='string'&&s.fields&&typeof s.fields==='object'&&(!s.original||Array.isArray(s.feedback)));}
for(const k of ['name','question','changes','overlap','selection','ai'])$(k).addEventListener('input',save);
$('add').onclick=()=>add();
function gaps(){const g=[];for(const k of ['name','question','changes','ai'])if(!state.fields[k]?.trim())g.push(k);state.sources.forEach((s,i)=>{for(const [k,l]of [...common,...matrixFields])if(!['doi','citation','population'].includes(k)&&!s.fields[k]?.trim())g.push('Source '+(i+1)+': '+l);if(!s.fields.type)g.push('Source '+(i+1)+': source family');if(!s.original)g.push('Source '+(i+1)+': guided feedback checkpoint');else if(!s.response?.trim()||!s.revision?.trim())g.push('Source '+(i+1)+': feedback response / revision (explain if unchanged)');});return g;}
$('check').onclick=()=>{save();const g=gaps(),p=state.sources.filter(s=>s.fields.type==='primary'&&s.fields.decision!=='replace').length,r=state.sources.filter(s=>s.fields.type==='review'&&s.fields.decision!=='replace').length,d=state.sources.filter(s=>deepFields.every(([k])=>s.fields[k]?.trim())).length;status('Recorded: '+p+' primary studies, '+r+' systematic reviews, '+d+' complete deeper appraisals. Final target: at least 4 primary, 1 review, and 2 deeper appraisals; follow Canvas for your current checkpoint. '+(g.length?'Missing records: '+g.join('; '):'No missing core records found. This does not establish accuracy or approval.'));};
function record(parent,label,value){const div=el('div');div.className='record';div.append(el('b',label));const p=el('p');if(/^https?:\/\/\S+$/.test(value||'')){const a=el('a',value);a.href=value;p.append(a);}else p.textContent=value||'[Not recorded]';div.append(p);parent.append(div);}
$('preview').onclick=()=>{save();const report=$('report');report.replaceChildren();report.hidden=false;const actions=el('div');actions.className='actions no-print';const print=el('button','Print / Save PDF');print.onclick=()=>window.print();const close=el('button','Return to workspace');close.onclick=()=>{report.hidden=true;$('workspace').hidden=false;};actions.append(print,close);report.append(actions,el('h1','Evidence Appraisal: Process Record'));record(report,'Your name',state.fields.name);record(report,'Current question',state.fields.question);record(report,'Question changes',state.fields.changes);state.sources.forEach((s,i)=>{const sec=el('section');sec.className='report-section';sec.append(el('h2','Source '+(i+1)));record(sec,'Source family',s.fields.type);for(const [k,l]of [...common,...matrixFields,...deepFields,['database','Database / discovery route'],['keywords','Search terms'],['decision','Current selection decision']])record(sec,l,s.fields[k]);record(sec,'Condition assignment',s.fields.assignment);record(sec,'Concern category',s.fields.concern);if(s.original){record(sec,'Preserved first appraisal','The entries above are your current working record. The first saved appraisal and subsequent checkpoints follow.');for(const [k,l]of [...common,...matrixFields,...deepFields])if(s.original[k])record(sec,'First checkpoint: '+l,s.original[k]);for(const [i,c]of (s.checkpoints||[]).entries()){record(sec,'Checkpoint '+(i+1)+' saved',c.savedAt);for(const [k,l]of [...common,...matrixFields,...deepFields])if(c.fields[k])record(sec,'Checkpoint '+(i+1)+': '+l,c.fields[k]);}record(sec,'Guided prompts',s.feedback.join('\n'));for(const [k,l]of [['response','Response to guided prompts'],['external','Peer / instructor feedback'],['revision','Revision and explanation'],['next','Next check']])record(sec,l,s[k]);}report.append(sec);});const end=el('section');end.className='report-section';for(const [k,l]of [['overlap','Source overlap check'],['selection','Evidence-set decisions'],['ai','AI-use statement']])record(end,l,state.fields[k]);report.append(end);$('workspace').hidden=true;report.scrollIntoView();};
$('backupTop').onclick=()=>$('backup').click();
$('backup').onclick=()=>{save();const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='evidence-appraisal-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function readFile(e){const f=e.target.files[0];if(!f)return null;if(f.size>110000000)throw Error('Backup exceeds the 110 MB limit.');return JSON.parse(await f.text());}
$('restore').onchange=async e=>{try{const d=await readFile(e);if(!valid(d))throw Error('Choose an Evidence Appraisal project backup.');if(confirm('Replace the current appraisal workspace with this backup? Save your current backup first if needed.')){apply(d);save();status('Appraisal backup restored.');}}catch(err){status(err.message);}e.target.value='';};
$('searchImport').onchange=async e=>{try{const d=await readFile(e);if(!d?.fields||d.version!==1||!('question'in d.fields))throw Error('Choose your Search → Review → Revise backup.');if(state.sources.length||$('question').value.trim())throw Error('Import into an empty appraisal workspace to avoid overwriting work. Save this workspace first, or enter candidate details manually.');$('name').value=d.fields.name||'';$('question').value=d.fields.question||'';save();for(const prefix of ['primary','review']){const fields={type:prefix==='primary'?'primary':'review'};for(const k of ['title','authors','year','journal','doi','link'])fields[k]=d.fields[prefix+k]||d.fields[prefix+'-'+k]||d.fields[prefix+'_'+k]||'';fields.citation=d.fields[prefix+'citation']||'';fields.link=d.fields[prefix+'url']||'';fields.design=d.fields[prefix+'design']||'';fields.access=d.fields[prefix+'access']||'';add(fields);}status('Question imported. Check candidate details against your sources; complete any fields not present in your search backup.');}catch(err){status(err.message);}e.target.value='';};
try{const stored=JSON.parse(localStorage.getItem(KEY));if(valid(stored))apply(stored);else render();}catch{render();}
