'use strict';
const $=id=>document.getElementById(id), KEY='exs290-evidence-appraisal-v1';
const common=[['citation','Imported candidate citation (verify and separate details below)'],['title','Article title'],['authors','Authors'],['year','Publication year'],['journal','Journal / publisher'],['doi','DOI, if available'],['link','Full-text link'],['access','Full-text access check and date'],['design','Specific study design or source type, and evidence supporting it'],['population','Population, conditions, comparison, and outcome relevant to your question'],['methods','Exact short methods excerpt and precise locator'],['methodMeaning','What do those methods tell you about how this evidence was produced?'],['result','Exact relevant result excerpt, including statistical support where applicable, and precise locator'],['interpretation','What does this finding mean? Explain in your own words.'],['strengthEvidence','One specific methodological strength: source evidence and locator'],['strengthMeaning','How does that strength affect confidence in this finding?'],['concernEvidence','One specific concern or limitation: source evidence and locator'],['consequence','What does that concern change about interpretation or use of this finding?'],['relevance','How does this source fit your question? Identify important mismatches.']];
const deepFields=[['deepEvidence','Evidence and locator for a consequential methodological issue'],['deepOrigin','What do the authors acknowledge, and what do you independently notice?'],['deepMeaning','How does this affect credibility, precision, applicability, or more than one? Explain.'],['weight','How does this change the weight you would give this source?']];
let state={kind:'exs290-appraisal',version:1,fields:{},sources:[]};
function status(t){$('status').textContent=t;}
function save(){for(const k of ['name','question','changes','overlap','selection','ai'])state.fields[k]=$(k).value;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{status('Browser storage is unavailable or full. Save a work backup to preserve your entries.');}}
function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
function input(parent,s,key,label,selectOptions){const id='s'+s.id+'-'+key,l=el('label',label);l.htmlFor=id;parent.append(l);const n=el(selectOptions?'select':(['title','authors','year','journal','doi','link','access'].includes(key)?'input':'textarea'));n.id=id;if(selectOptions)for(const [v,t]of selectOptions){const o=el('option',t);o.value=v;n.append(o);}n.value=s.fields[key]||'';if(s.original&&!deepFields.some(([k])=>k===key)){if(n.tagName==='SELECT')n.disabled=true;else n.readOnly=true;}n.addEventListener('input',()=>{s.fields[key]=n.value;save();});parent.append(n);return n;}
function prompts(s){const f=s.fields,p=[];if(f.type==='primary'){p.push(f.assignment==='assigned'?'Check how assignment, the comparison condition, missing data, and measurement could affect the finding. Assignment alone does not establish that bias was prevented.':'Check whether your wording implies causation. What features of the actual design support or limit that interpretation?');}else if(f.type==='review')p.push('Check databases and search dates, eligibility rules, appraisal of included studies, and how findings were combined. Do differences among included studies affect the synthesis?');else p.push('Check how evidence was selected and how recommendations were developed. Distinguish supporting research from expert judgment and disclose conflicts or missing process information.');
const concerns={sample:'Is the sample concern about precision, representation, or both? Locate the specific evidence and explain the consequence.',measurement:'Check what the measure captures, how consistently it was collected, and whether it matches your intended outcome.',bias:'Identify the specific pathway through which selection, confounding, blinding, missing data, or reporting could influence the result.',applicability:'Which population, setting, dose, outcome, or time frame differs from your question? Explain how that limits use.',reporting:'Separate information not reported from evidence that a method was not used. What remains uncertain?',other:'Explain how the concern could influence this specific result or its use. Avoid a generic limitation list.'};p.push(concerns[f.concern]||concerns.other);p.push('Recheck the exact comparison, units, time point, and statistical information. A significant result is not automatically practically important; a nonsignificant result does not establish equivalence.');return p;}
function render(){const host=$('sources');host.replaceChildren();state.sources.forEach((s,index)=>{const box=el('fieldset'),legend=el('legend','Source '+(index+1));box.append(legend);input(box,s,'type','Source family',[['','Choose a source family'],['primary','Primary study'],['review','Systematic review / meta-analysis'],['position','Position stand (when allowed)']]);
const guide=el('p',s.fields.type==='review'?'Review methods: examine searching, eligibility, study appraisal, and synthesis.':s.fields.type==='position'?'Position stand: examine evidence selection, recommendation development, and conflicts of interest.':'Primary methods: examine recruitment, assignment or observation, comparison, measurement, and analysis.');guide.className='hint';box.append(guide);const groups=[['1. Identify and verify the source',common.slice(0,9)],['2. Examine the methods',common.slice(9,12)],['3. Interpret a relevant finding',common.slice(12,14)],['4. Judge strengths, concerns, and fit',common.slice(14)]];for(const [heading,fields]of groups){const panel=el('details');panel.open=index===0;panel.append(el('summary',heading));for(const [k,l]of fields)input(panel,s,k,l);box.append(panel);}
input(box,s,'assignment','For a primary study, were conditions assigned or observed?',[['','Choose / not applicable'],['assigned','Assigned by researchers'],['observed','Observed / not assigned'],['na','Not applicable to this source']]);input(box,s,'concern','What is your main concern?',[['','Choose a concern'],['sample','Sample size or representation'],['measurement','Measurement'],['bias','Bias or confounding'],['applicability','Applicability'],['reporting','Incomplete reporting'],['other','Other / uncertainty']]);
const deep=el('details');deep.append(el('summary','Deeper appraisal (complete for two influential sources)'));for(const [k,l]of deepFields)input(deep,s,k,l);box.append(deep);
const feedback=el('div');feedback.className='feedback';feedback.append(el('h3','Guided feedback and revision'));feedback.append(el('p','These prompts are selected from your structured choices. They do not evaluate your article, verify your interpretation, or generate an answer.'));
if(!s.original){const b=el('button','Save my first appraisal and show prompts');b.addEventListener('click',()=>{save();const missing=['type','methods','methodMeaning','result','interpretation','strengthEvidence','strengthMeaning','concernEvidence','consequence','relevance','concern'].filter(k=>!s.fields[k]?.trim());if(missing.length){status('Complete source '+(index+1)+' evidence, interpretation, strength, concern, relevance, and choices before requesting prompts.');return;}s.original=JSON.parse(JSON.stringify(s.fields));s.feedback=prompts(s);save();render();status('Original appraisal preserved. Record your response and corrections below.');});feedback.append(b);}else{feedback.append(el('p','Original appraisal saved. Corrections belong below; the PDF retains the original.'));const ul=el('ul');for(const p of s.feedback)ul.append(el('li',p));feedback.append(ul);for(const [k,l]of [['response','Which prompts will you adopt, adapt, or decline, and why?'],['external','Peer / instructor feedback: who provided it and what was suggested?'],['revision','Your revised interpretation or appraisal: identify what changed and why'],['next','What remains uncertain, and what will you check next?']]){const id='s'+s.id+'-'+k,lbl=el('label',l);lbl.htmlFor=id;const n=el('textarea');n.id=id;n.value=s[k]||'';n.addEventListener('input',()=>{s[k]=n.value;save();});feedback.append(lbl,n);}}
box.append(feedback);host.append(box);const type=$('s'+s.id+'-type');type.addEventListener('change',render);});}
function add(fields={}){state.sources.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),fields});save();render();}
function apply(data){state=data;for(const k of ['name','question','changes','overlap','selection','ai'])$(k).value=state.fields[k]||'';render();}
function valid(d){return d?.kind==='exs290-appraisal'&&d.version===1&&d.fields&&Array.isArray(d.sources)&&d.sources.length<=30&&d.sources.every(s=>typeof s.id==='string'&&s.fields&&typeof s.fields==='object'&&(!s.original||Array.isArray(s.feedback)));}
for(const k of ['name','question','changes','overlap','selection','ai'])$(k).addEventListener('input',save);
$('add').onclick=()=>add();
function gaps(){const g=[];for(const k of ['name','question','changes','ai'])if(!state.fields[k]?.trim())g.push(k);state.sources.forEach((s,i)=>{for(const [k,l]of common)if(!['doi','citation'].includes(k)&&!s.fields[k]?.trim())g.push('Source '+(i+1)+': '+l);if(!s.fields.type)g.push('Source '+(i+1)+': source family');if(!s.original)g.push('Source '+(i+1)+': guided feedback checkpoint');else if(!s.response?.trim()||!s.revision?.trim())g.push('Source '+(i+1)+': feedback response / revision (explain if unchanged)');});return g;}
$('check').onclick=()=>{save();const g=gaps(),p=state.sources.filter(s=>s.fields.type==='primary').length,r=state.sources.filter(s=>s.fields.type==='review').length,d=state.sources.filter(s=>deepFields.every(([k])=>s.fields[k]?.trim())).length;status('Recorded: '+p+' primary studies, '+r+' systematic reviews, '+d+' complete deeper appraisals. Final target: at least 4 primary, 1 review, and 2 deeper appraisals; follow Canvas for your current checkpoint. '+(g.length?'Missing records: '+g.join('; '):'No missing core records found. This does not establish accuracy or approval.'));};
function record(parent,label,value){const div=el('div');div.className='record';div.append(el('b',label));const p=el('p');if(/^https?:\/\/\S+$/.test(value||'')){const a=el('a',value);a.href=value;p.append(a);}else p.textContent=value||'[Not recorded]';div.append(p);parent.append(div);}
$('preview').onclick=()=>{save();const report=$('report');report.replaceChildren();report.hidden=false;const actions=el('div');actions.className='actions no-print';const print=el('button','Print / Save PDF');print.onclick=()=>window.print();const close=el('button','Return to workspace');close.onclick=()=>{report.hidden=true;$('workspace').hidden=false;};actions.append(print,close);report.append(actions,el('h1','Evidence Appraisal: Process Record'));record(report,'Your name',state.fields.name);record(report,'Current question',state.fields.question);record(report,'Question changes',state.fields.changes);state.sources.forEach((s,i)=>{const sec=el('section');sec.className='report-section';sec.append(el('h2','Source '+(i+1)));record(sec,'Source family',s.fields.type);for(const [k,l]of [...common,...deepFields])record(sec,l,s.fields[k]);record(sec,'Condition assignment',s.fields.assignment);record(sec,'Concern category',s.fields.concern);if(s.original){record(sec,'Preserved first appraisal','The entries above are the saved original. Later feedback responses and corrections follow.');for(const [k,l] of deepFields)if(s.original[k])record(sec,'Original deeper appraisal: '+l,s.original[k]);record(sec,'Guided prompts',s.feedback.join('\n'));for(const [k,l]of [['response','Response to guided prompts'],['external','Peer / instructor feedback'],['revision','Revision and explanation'],['next','Next check']])record(sec,l,s[k]);}report.append(sec);});const end=el('section');end.className='report-section';for(const [k,l]of [['overlap','Source overlap check'],['selection','Evidence-set decisions'],['ai','AI-use statement']])record(end,l,state.fields[k]);report.append(end);$('workspace').hidden=true;report.scrollIntoView();};
$('backup').onclick=()=>{save();const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='evidence-appraisal-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function readFile(e){const f=e.target.files[0];if(!f)return null;if(f.size>110000000)throw Error('Backup exceeds the 110 MB limit.');return JSON.parse(await f.text());}
$('restore').onchange=async e=>{try{const d=await readFile(e);if(!valid(d))throw Error('Choose an Evidence Appraisal project backup.');if(confirm('Replace the current appraisal workspace with this backup? Save your current backup first if needed.')){apply(d);save();status('Appraisal backup restored.');}}catch(err){status(err.message);}e.target.value='';};
$('searchImport').onchange=async e=>{try{const d=await readFile(e);if(!d?.fields||d.version!==1||!('question'in d.fields))throw Error('Choose your Search → Review → Revise backup.');if(state.sources.length||$('question').value.trim())throw Error('Import into an empty appraisal workspace to avoid overwriting work. Save this workspace first, or enter candidate details manually.');$('name').value=d.fields.name||'';$('question').value=d.fields.question||'';save();for(const prefix of ['primary','review']){const fields={type:prefix==='primary'?'primary':'review'};for(const k of ['title','authors','year','journal','doi','link'])fields[k]=d.fields[prefix+k]||d.fields[prefix+'-'+k]||d.fields[prefix+'_'+k]||'';fields.citation=d.fields[prefix+'citation']||'';fields.link=d.fields[prefix+'url']||'';fields.design=d.fields[prefix+'design']||'';fields.access=d.fields[prefix+'access']||'';add(fields);}status('Question imported. Check candidate details against your sources; complete any fields not present in your search backup.');}catch(err){status(err.message);}e.target.value='';};
try{const stored=JSON.parse(localStorage.getItem(KEY));if(valid(stored))apply(stored);else render();}catch{render();}
